#DataBase configuration
spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name=sofftek:us-central1:inventario
spring.datasource.url=jdbc:postgresql:///inventario
spring.cloud.gcp.sql.database-name=inventario
spring.datasource.username=postgres
spring.datasource.password=T3cn0M0tum!
spring.jpa.hibernate.ddl-auto=update
spring.cloud.gcp.credentials.location=file:${GOOGLE_CREDENTIALS_COMERCIAL}
#keycloak Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://authentication-api-374227089883.us-central1.run.app/realms/inventario
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://authentication-api-374227089883.us-central1.run.app/realms/inventario/protocol/openid-connect/certs
logging.level.org.keycloak=DEBUG
jwt.auth.converter.principleAttribute=preferred_username
jwt.auth.converter.resource-id=inventario