spring.application.name=inventario

spring.datasource.url=jdbc:postgresql://localhost:5433/inventario

spring.datasource.username=postgres
spring.datasource.password=T3cn0M0tum!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=false
#keycloak Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/inventario
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/inventario/protocol/openid-connect/certs
logging.level.org.keycloak=DEBUG
jwt.auth.converter.principleAttribute=preferred_username
jwt.auth.converter.resource-id=inventario